# knowledge_base.py
# Base de conocimiento para detección de habilidades con zero-shot
# Agregar aquí nuevas carreras o tecnologías sin tocar el código principal

CANDIDATOS = [
    # ── Tecnología / Ingeniería de Software ──────────────────────
    "Python programming",
    "JavaScript web development",
    "Java programming",
    "mobile app development Android iOS",
    "Flutter Dart development",
    "SQL databases",
    "NoSQL MongoDB databases",
    "cloud computing AWS Azure GCP",
    "cybersecurity network security",
    "computer networks Cisco routing",
    "machine learning artificial intelligence",
    "deep learning neural networks",
    "Linux operating systems",
    "Docker containers DevOps",
    "Git version control",
    "software engineering",
    "data structures algorithms",
    "web development frontend backend",
    "REST API development",
    "compiler design automata theory",
    "software quality testing",
    "user interface design UX",
    "blockchain cryptocurrency",
    "data analysis visualization",
    "embedded systems electronics",
    "operating systems processes memory",
    "computer architecture assembly",
    "numerical methods simulation",

    # ── Administración / Negocios ─────────────────────────────────
    "project management",
    "leadership management",
    "financial analysis accounting",
    "marketing business strategy",
    "human resources management",
    "supply chain logistics",
    "entrepreneurship innovation",
    "business intelligence",
    "organizational behavior",
    "economics microeconomics macroeconomics",
    "international business trade",
    "sales customer service",
    "quality management ISO",

    # ── Ciencias de la Salud ──────────────────────────────────────
    "anatomy physiology biology",
    "medicine clinical practice",
    "pharmacology drugs treatment",
    "nursing patient care",
    "public health epidemiology",
    "psychology mental health",
    "nutrition dietetics food science",
    "dentistry oral health",
    "veterinary animal health",
    "biochemistry molecular biology",
    "medical laboratory clinical analysis",
    "physical therapy rehabilitation",

    # ── Ciencias Exactas ──────────────────────────────────────────
    "mathematics statistics probability",
    "physics mechanics thermodynamics",
    "chemistry laboratory reactions",
    "calculus differential equations",
    "linear algebra discrete mathematics",
    "biology ecology genetics",
    "geology earth sciences",
    "astronomy astrophysics",

    # ── Humanidades / Ciencias Sociales ───────────────────────────
    "English language communication",
    "writing literature reading",
    "law legal studies jurisprudence",
    "history social sciences",
    "ethics philosophy",
    "sociology anthropology",
    "political science government",
    "education pedagogy teaching",
    "linguistics translation",
    "geography urban studies",

    # ── Diseño / Arte / Comunicación ─────────────────────────────
    "graphic design visual arts",
    "architecture urban planning",
    "multimedia animation video",
    "photography audiovisual production",
    "industrial design product design",
    "fashion textile design",
    "music audio production",
    "journalism media communication",
    "advertising public relations",

    # ── Ingeniería (otras ramas) ──────────────────────────────────
    "civil structural engineering",
    "mechanical engineering manufacturing",
    "electrical engineering power systems",
    "industrial engineering operations",
    "environmental engineering sustainability",
    "chemical engineering processes",
    "aerospace aeronautical engineering",
    "biomedical engineering",
    "petroleum mining engineering",
    "agricultural engineering food technology",
]

NOMBRE_ES = {
    # Tecnología
    "Python programming":                         "Python",
    "JavaScript web development":                 "JavaScript / Web",
    "Java programming":                           "Java",
    "mobile app development Android iOS":         "Desarrollo Móvil",
    "Flutter Dart development":                   "Flutter / Dart",
    "SQL databases":                              "SQL / Bases de Datos",
    "NoSQL MongoDB databases":                    "MongoDB / NoSQL",
    "cloud computing AWS Azure GCP":              "Cloud Computing",
    "cybersecurity network security":             "Ciberseguridad",
    "computer networks Cisco routing":            "Redes / Cisco",
    "machine learning artificial intelligence":   "Machine Learning / IA",
    "deep learning neural networks":              "Deep Learning",
    "Linux operating systems":                    "Linux / Sistemas Operativos",
    "Docker containers DevOps":                   "Docker / DevOps",
    "Git version control":                        "Git / Control de Versiones",
    "software engineering":                       "Ingeniería de Software",
    "data structures algorithms":                 "Estructuras de Datos",
    "web development frontend backend":           "Desarrollo Web",
    "REST API development":                       "APIs REST",
    "compiler design automata theory":            "Compiladores / Autómatas",
    "software quality testing":                   "Calidad de Software",
    "user interface design UX":                   "Diseño UI/UX",
    "blockchain cryptocurrency":                  "Blockchain",
    "data analysis visualization":                "Análisis de Datos",
    "embedded systems electronics":               "Sistemas Embebidos",
    "operating systems processes memory":         "Sistemas Operativos",
    "computer architecture assembly":             "Arquitectura de Computadoras",
    "numerical methods simulation":               "Métodos Numéricos",
    # Administración
    "project management":                         "Administración de Proyectos",
    "leadership management":                      "Liderazgo / Gestión",
    "financial analysis accounting":              "Análisis Financiero",
    "marketing business strategy":                "Marketing / Estrategia",
    "human resources management":                 "Recursos Humanos",
    "supply chain logistics":                     "Cadena de Suministro",
    "entrepreneurship innovation":                "Emprendimiento",
    "business intelligence":                      "Inteligencia de Negocios",
    "organizational behavior":                    "Comportamiento Organizacional",
    "economics microeconomics macroeconomics":    "Economía",
    "international business trade":               "Negocios Internacionales",
    "sales customer service":                     "Ventas / Atención al Cliente",
    "quality management ISO":                     "Gestión de Calidad",
    # Salud
    "anatomy physiology biology":                 "Anatomía / Fisiología",
    "medicine clinical practice":                 "Medicina Clínica",
    "pharmacology drugs treatment":               "Farmacología",
    "nursing patient care":                       "Enfermería",
    "public health epidemiology":                 "Salud Pública",
    "psychology mental health":                   "Psicología",
    "nutrition dietetics food science":           "Nutrición",
    "dentistry oral health":                      "Odontología",
    "veterinary animal health":                   "Veterinaria",
    "biochemistry molecular biology":             "Bioquímica / Biología Molecular",
    "medical laboratory clinical analysis":       "Laboratorio Clínico",
    "physical therapy rehabilitation":            "Fisioterapia / Rehabilitación",
    # Ciencias
    "mathematics statistics probability":         "Matemáticas / Estadística",
    "physics mechanics thermodynamics":           "Física",
    "chemistry laboratory reactions":             "Química",
    "calculus differential equations":            "Cálculo",
    "linear algebra discrete mathematics":        "Álgebra / Matemáticas Discretas",
    "biology ecology genetics":                   "Biología / Ecología",
    "geology earth sciences":                     "Geología",
    "astronomy astrophysics":                     "Astronomía",
    # Humanidades
    "English language communication":             "Inglés",
    "writing literature reading":                 "Escritura / Literatura",
    "law legal studies jurisprudence":            "Derecho",
    "history social sciences":                    "Historia / Ciencias Sociales",
    "ethics philosophy":                          "Ética / Filosofía",
    "sociology anthropology":                     "Sociología / Antropología",
    "political science government":               "Ciencias Políticas",
    "education pedagogy teaching":                "Educación / Pedagogía",
    "linguistics translation":                    "Lingüística / Traducción",
    "geography urban studies":                    "Geografía / Estudios Urbanos",
    # Diseño
    "graphic design visual arts":                 "Diseño Gráfico",
    "architecture urban planning":                "Arquitectura",
    "multimedia animation video":                 "Multimedia / Animación",
    "photography audiovisual production":         "Fotografía / Audiovisual",
    "industrial design product design":           "Diseño Industrial",
    "fashion textile design":                     "Diseño de Moda",
    "music audio production":                     "Música / Producción de Audio",
    "journalism media communication":             "Periodismo / Comunicación",
    "advertising public relations":               "Publicidad / Relaciones Públicas",
    # Ingeniería
    "civil structural engineering":               "Ingeniería Civil",
    "mechanical engineering manufacturing":       "Ingeniería Mecánica",
    "electrical engineering power systems":       "Ingeniería Eléctrica",
    "industrial engineering operations":          "Ingeniería Industrial",
    "environmental engineering sustainability":   "Ingeniería Ambiental",
    "chemical engineering processes":             "Ingeniería Química",
    "aerospace aeronautical engineering":         "Ingeniería Aeroespacial",
    "biomedical engineering":                     "Ingeniería Biomédica",
    "petroleum mining engineering":               "Ingeniería Petrolera / Minera",
    "agricultural engineering food technology":   "Ingeniería Agrícola / Alimentaria",
}

# Mapa para unificar duplicados entre nlp_processor y tech_extractor
UNIFICAR = {
    "Cloud / AWS":               "Cloud Computing",
    "Móvil / Android":           "Desarrollo Móvil",
    "Web":                       "Desarrollo Web",
    "Redes":                     "Redes / Cisco",
    "Bases de datos":            "SQL / Bases de Datos",
    "IA / ML":                   "Machine Learning / IA",
    "Sistemas":                  "Linux / Sistemas Operativos",
}